# use MSSQL 2017 image on Ubuntu 16.04
FROM microsoft/mssql-server-linux:2017-latest

# create directory within SQL container for database files
RUN mkdir -p /opt/mssql-scripts

# copy the database files from host to container
COPY CREATE_AUTHORIZATIONDB1.sql /opt/mssql-scripts

# set environment variables
ENV MSSQL_SA_PASSWORD=@AuthorizationDB1
ENV ACCEPT_EULA=Y

# run initial scripts
RUN /opt/mssql/bin/sqlservr --accept-eula & sleep 10 \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '@AuthorizationDB1' -i /opt/mssql-scripts/CREATE_AUTHORIZATIONDB1.sql\
    && pkill sqlservr 
